name: Publish .NET Package to NuGet

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build ./TemplatePackage/TemplatePackage.csproj --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack ./TemplatePackage/TemplatePackage.csproj --configuration Release --no-build --output ./nupkg

      - name: Login to NuGet.org using OIDC
        id: login
        uses: NuGet/login@v1
        with:
          user: PalmForest

      - name: Push the package to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
